[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:bgutil]
command=node /app/bgutil/build/main.js
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:vvp]
command=node /app/vvp/server.js
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
